name: First Settings
description: Generate a JSON configuration with application name, theme, and menu tabs
inputs:
  appName:
    description: "Application name"
    required: true
  theme:
    description: "Choose theme (light or dark)"
    required: true
    default: "light"
  menuTabs:
    description: "Menu tabs separated by commas (e.g., Dashboard,Compras)"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Run First Settings Script
      shell: bash
      run: |
        ./first-settings.sh "${{ inputs.appName }}" "${{ inputs.theme }}" "${{ inputs.menuTabs }}"
    - name: Upload JSON artifact
      uses: actions/upload-artifact@v3
      with:
        name: settings-json
        path: settings.json
