---
name: Project Initialization Pipeline

on:
  workflow_dispatch:
    inputs:
      projectName:
        description: "Name of the project"
        required: true

jobs:
  setup-project:
    runs-on: ubuntu-latest

    outputs:
      FOLDER_NAME: ${{ steps.normalize.outputs.normalized-name }}

    steps:
      - name: Normalize project name
        id: normalize
        run: |
          NORMALIZED_NAME=$(echo "${{ github.event.inputs.projectName }}" | tr '[:upper:]' '[:lower:]' | sed 's/ /_/g')
          echo "normalized-name=$NORMALIZED_NAME" >> $GITHUB_OUTPUT

      - name: Create project directory
        run: |
          mkdir -p "$HOME/git"
          echo "Created base directory: $HOME/git"

          PROJECT_DIR="$HOME/git/${{ steps.normalize.outputs.normalized-name }}"
          mkdir -p "$PROJECT_DIR"
          echo "Project directory created at: $PROJECT_DIR"

  setup-frontend:
    needs: setup-project
    runs-on: ubuntu-latest
    env:
      FOLDER_NAME: ${{ needs.setup-project.outputs.FOLDER_NAME }}

    steps:
      - name: Set up frontend
        run: |
          PROJECT_DIR="$HOME/git/$FOLDER_NAME"
          cd "$PROJECT_DIR"
          npx create-react-app frontend --use-npm --template cra-template
          echo "Frontend setup completed"

  setup-backend:
    needs: setup-frontend
    runs-on: ubuntu-latest
    env:
      FOLDER_NAME: ${{ needs.setup-project.outputs.FOLDER_NAME }}

    steps:
      - name: Set up backend
        run: |
          PROJECT_DIR="$HOME/git/$FOLDER_NAME"
          cd "$PROJECT_DIR"
          mkdir backend
          cd backend
          npm init -y
          echo '{"scripts": {"dev": "nodemon server.js"}}' > package.json
          echo "Backend setup completed"

  create-repo:
    needs: setup-backend
    runs-on: ubuntu-latest
    env:
      FOLDER_NAME: ${{ needs.setup-project.outputs.FOLDER_NAME }}

    steps:
      - name: Create repository on GitHub
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -d "{\"name\": \"$FOLDER_NAME\", \"private\": true}" \
            https://api.github.com/user/repos

  commit-and-push:
    needs: create-repo
    runs-on: ubuntu-latest
    env:
      FOLDER_NAME: ${{ needs.setup-project.outputs.FOLDER_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Commit and push project
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          PROJECT_DIR="$HOME/git/$FOLDER_NAME"
          cd "$PROJECT_DIR"
          git init
          git add .
          git commit -m "Initialize project: ${{ github.event.inputs.projectName }}"
          git branch -M main
          git remote add origin https://github.com/$USERNAME/$FOLDER_NAME.git
          git push -u origin main
