---
on:
  workflow_dispatch:
    inputs:
      appName:
        description: "Application name"
        required: true
      theme:
        description: "Choose theme (light or dark)"
        default: "light"
      menuTabs:
        description: "Menu tabs separated by commas (e.g., Dashboard,Compras)"
        default: ""

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Palette JSON
        uses: ./.github/actions/generate-palette
        with:
          appName: ${{ github.event.inputs.appName }}
          theme: ${{ github.event.inputs.theme }}
          menuTabs: ${{ github.event.inputs.menuTabs }}

      - name: Download JSON artifact
        uses: actions/download-artifact@v3
        with:
          name: palette-json

      - name: Show JSON
        run: cat palette.json
