---
name: Project Initialization Pipeline

on:
  workflow_dispatch:
    inputs:
      projectName:
        description: "Name of the project"
        required: true
      # theme:
      #   description: "Choose theme (light or dark)"
      #   default: "light"
      # menuTabs:
      #   description: "Menu tabs separated by commas (e.g., Dashboard,Compras)"
      #   default: ""

jobs:
  setup-project:
    runs-on: ubuntu-latest

    steps:
      - name: Normalize project name
        id: normalize
        run: |
          NORMALIZED_NAME=$(echo "${{ github.event.inputs.projectName }}" | tr '[:upper:]' '[:lower:]' | sed 's/ /_/g')
          echo "NORMALIZED_NAME=$NORMALIZED_NAME" >> $GITHUB_ENV

      - name: Create project directory
        run: |
          PROJECT_DIR="$HOME/git/$NORMALIZED_NAME"
          mkdir -p "$PROJECT_DIR"
          echo "Project directory created at: $PROJECT_DIR"

  setup-frontend:
    needs: setup-project
    runs-on: ubuntu-latest

    steps:
      - name: Set up frontend
        run: |
          PROJECT_DIR="$HOME/git/$NORMALIZED_NAME"
          cd "$PROJECT_DIR"
          npx create-react-app frontend
          cd frontend
          npm install axios react-router-dom react-toastify
          echo "Frontend setup completed"

  setup-backend:
    needs: setup-frontend
    runs-on: ubuntu-latest

    steps:
      - name: Set up backend
        run: |
          PROJECT_DIR="$HOME/git/$NORMALIZED_NAME"
          cd "$PROJECT_DIR"
          mkdir backend
          cd backend
          npm init -y
          npm install express cors jsonwebtoken dotenv bcryptjs multer mongoose
          npm install -D nodemon
          echo '{"scripts": {"dev": "nodemon server.js"}}' > package.json
          echo "Backend setup completed"